{
 "title": "Inventory",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Avarage Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(db_read_latency_seconds_sum{job=\"inventory\"}[5m]) / rate(db_read_latency_seconds_count{job=\"inventory\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avarage write latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(db_write_latency_seconds_sum{job=\"inventory\"}[5m]) / rate(db_write_latency_seconds_count{job=\"inventory\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"5xx\", job=\"inventory\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "AVG Not found items through the day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(items_not_found_total{job=\"inventory\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Reservations per day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(inventory_successful_reservations{job=\"inventory\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"inventory\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Average number of missing items (last day)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(inventory_not_enough_stock_missing_items_sum{job=\"inventory\"}[1d]))\n/\nsum(rate(inventory_not_enough_stock_missing_items_count{job=\"inventory\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"inventory\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"inventory\"}[1m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=\"inventory\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"inventory\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=\"inventory\",handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\", job=\"inventory\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count{job=\"inventory\"}[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{handler!=\"none\", job=\"inventory\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}